# 
# Copyright 2025 Darrel Courrier.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
; empty line
// comment next line is null

= missing key
key =
goodKey = value            ;  see if trailing spaces are lost
key1 = new value;
Key1 = New Value;
#Legitimate values are XML, RDBMS, simple file, JNDI, Hibernate, EJB (not case sensitive), 
#EJBLOCAL,, JSON, REST, DOTNET, ODB, DERBY, DERBYNET
com.courrier.PersistenceType=Hibernate
#com.courrier.PersistenceType=RDBMS
#com.courrier.PersistenceType=simple file
com.courrier.PersistenceLocation=c:/pgms/Data/volunteer
com.courrier.SimpleFileName=VolunteerScheduler.DAT
com.courrier.maxSaveCount=100
com.courrier.PDF.Location=c:/pgms/Data/volunteer/Reports

com.courrier.XMLFile=VolunteerSchedulerData.xml
com.courrier.XMLDocTypeDef=VolunteerSchedulerData.dtd
com.courrier.queryMap=VolSchedQueryMap.xml
com.courrier.entityMap=VolSchedEntityMap.xml

com.courrier.login.maxFail=3
com.courrier.login.password.minLength=8
com.courrier.login.secret.minLength=3
com.courrier.login.old.password.check.months=12
com.courrier.login.password.expire.days=12
com.courrier.login.admin=Admin
com.courrier.login.system.id=SystemUtilities
com.courrier.login.public=Home,Not Authorized,Password Reset

com.courrier.odb.location=C:\PerstData
com.courrier.perst.file= C:/PerstData/Volsched.odb
com.courrier.perst.pagePoolSize=34000000

com.courrier.JNDI.INITIAL_CONTEXT_FACTORY=com.sun.jndi.ldap.LdapCtxFactory
com.courrier.JNDI.PROVIDER_URL=ldap://Laptop1:10389
com.courrier.JNDI.SECURITY_PRINCIPAL=uid=admin,ou=system
com.courrier.JNDI.SECURITY_CREDENTIALS=secret
com.courrier.JNDI.ROOT=dc=volsched,dc=courrier,dc=com,ou=volsched
com.courrier.JNDI.BufferSize=16; number of k-bytes to use for serializing objects

com.courrier.EJB.Server.Type=GLASSFISH
#com.courrier.EJB.Server.Type=WEBLOGIC
#com.courrier.EJB.Server.Type=JBOSS
#com.courrier.EJB.Server.Type=PAYARA
#com.courrier.EJB.Server.Type=TOMCATEE
com.courrier.EJB.connect.timeout=3000
com.courrier.EJB.Glassfish.host=localhost
com.courrier.EJB.Glassfish.namingFactory=com.sun.enterprise.naming.SerialInitContextFactory
com.courrier.EJB.Glassfish.namingFactory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl
com.courrier.EJB.Glassfish.namingFactory.url=iiop://localhost:3703
com.courrier.EJB.Glassfish.port=3703
com.courrier.EJB.Glassfish.url.pkg=com.sun.enterprise.naming
com.courrier.EJB.Glassfish.volshed.remoteInterface=com.courrier.volunteer.persistence.ejb.VolunteerSchedulerBeanRemote
com.courrier.EJB.Glassfish.volshed.localInterface=java:global/MavenVolunteerSchedulerEARV5.1/VolunteerSchedulerLocalBean!com.courrier.volunteer.persistence.ejb.VolunteerSchedulerLocalBean

com.courrier.EJB.Weblogic.namingFactory=weblogic.jndi.WLInitialContextFactory
com.courrier.EJB.Weblogic.url=t3://localhost:7001
com.courrier.EJB.Weblogic.volshed.remoteInterface=java:global.VolunteerSchedulerWlsEAR.VolunteerSchedulerWlsEJB.VolunteerSchedulerBean

com.courrier.EJB.JBOSS.namingFactory=org.wildfly.naming.client.WildFlyInitialContextFactory
com.courrier.EJB.JBOSS.host=localhost
com.courrier.EJB.JBOSS.url=http-remoting://localhost:8182
com.courrier.EJB.JBOSS.port=8182
com.courrier.EJB.JBOSS.volshed.remoteInterface=VolunteerSchedulerWildflyEAR/VolunteerSchedulerWildflyEAR-ejb/VolunteerSchedulerBean!com.courrier.volunteer.persistence.ejb.VolunteerSchedulerBeanRemote
com.courrier.EJB.JBOSS.volshed.localInterface=VolunteerSchedulerWildflyEAR/VolunteerSchedulerWildflyEAR-ejb/VolunteerSchedulerLocalBean!com.courrier.volunteer.persistence.ejb.VolunteerSchedulerLocalBean


com.courrier.EJB.Payara.namingFactory=com.sun.enterprise.naming.SerialInitContextFactory
com.courrier.EJB.Payara.namingFactory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl
com.courrier.EJB.Payara.host=localhost
com.courrier.EJB.Payara.port=3701
com.courrier.EJB.Payara.namingFactory.url=iiop://localhost:3701
com.courrier.EJB.Payara.url.pkg=com.sun.enterprise.naming
com.courrier.EJB.Payara.volshed.remoteInterface=com.courrier.volunteer.persistence.ejb.VolunteerSchedulerBeanRemote
com.courrier.EJB.Payara.volshed.localInterface=java:global/VolunteerSchedulerPayaraEAR/VolunteerSchedulerPayaraEAR-ejb/VolunteerSchedulerLocalBean!com.courrier.volunteer.persistence.ejb.VolunteerSchedulerBeanLocal

com.courrier.email=dcourrier@aol.com

com.courrier.errorHandler.messageLevel=WARNING_ERROR

db.derby.driver.connectInfo=jdbc:derby://localhost:1528/volsched;create=true;user=volschedv5;
db.derby.driver.class=org.apache.derby.jdbc.ClientDriver
db.derby.databaseLocation=D:/DerbyData
db.derby.pool.size=20
db.derby.pool.timeout=30
db.derby.query.timeout=30
db.derby.port=1528
db.derby.host=localhost
db.derby.schema=volschedv5
db.derby.embedded.connectInfo=jdbc:derby:volsched;create=true;user=volschedv5
db.derby.embedded.driver=org.apache.derby.jdbc.EmbeddedDriver

com.courrier.REST.url=http://localhost:8380

com.courrier.DOTNET.url=http://?