from vs.bean.beans import SessionDataBean
class AuthorizationBean(SessionDataBean):
    
    resources: {
        'RESOURCE_ADD_ORGANIZATION': 'Add Organization',
        'RESOURCE_DELETE_ORGANIZATION': "Delete Organization",
        'RESOURCE_UPDATE_ORGANIZATION': "Update Organization",
        'RESOURCE_VIEW_EVENTS': "View Events",
        'RESOURCE_ORGANIZATIONS': "Update Organizations",
        'RESOURCE_ADD_ACTIVITY': "Add Activity",
        'RESOURCE_DELETE_ACTIVITY': "Delete Activity",
        'RESOURCE_UPDATE_ACTIVITY': "Update Activity",
        'RESOURCE_VIEW_ACTIVITIES': "View Activities",
        'RESOURCE_ADD_PROJECT': "add Project",
        'RESOURCE_DELETE_PROJECT': "Delete Project",
        'RESOURCE_UPDATE_PROJECT': "Update Project",
        'RESOURCE_VIEW_PROJECTS': "View Projects",
        'RESOURCE_ADD_TASK': "Add Project Task",
        'RESOURCE_DELETE_TASK': "Delete Project Task",
        'RESOURCE_UPDATE_TASK': "Update Project Task",
        'RESOURCE_VIEW_TASKS': "View Project Tasks",
        'RESOURCE_ADD_TEAM': "Add Project Team",
        'RESOURCE_DELETE_TEAM': "Delete Project Team",
        'RESOURCE_UPDATE_TEAM': "Update Project Team",
        'RESOURCE_VIEW_TEAMS': "View Project Teams",
        'RESOURCE_VIEW_LOGINS': "View Logins",
        'RESOURCE_DELETE_WORK_ADDRESS': "Delete Work Address",
        'RESOURCE_UPDATE_VOLUNTEER': "Update Volunteer",
        'RESOURCE_DELETE_SKILL': "Delete Skill",
        'RESOURCE_ADD_SCHEDULE': "Add Schedule",
        'RESOURCE_UPDATE_REPORT': "Update Report",
        'RESOURCE_VIEW_WORK_ADDRESS': "View Work Address",
        'RESOURCE_DELETE_RELATIONSHIP': "Delete Relationship",
        'RESOURCE_DELETE_SCHEDULE': "Delete Schedule",
        'RESOURCE_ADD_VOLUNTEER_SKILL': "Add Volunteer Skill",
        'RESOURCE_ADD_SECURITY_GROUP': "Add Security Group",
        'RESOURCE_VIEW_VOLUNTEERS':"View Volunteers",
        'RESOURCE_ADD_WORK_ADDRESS': "Add Work Address",
        'RESOURCE_UPDATE_AUTHORIZATION': "Update Authorization",
        'RESOURCE_VIEW_HOUSEHOLD': "View Household",
        'RESOURCE_VIEW_LOCATIONS': "View Locations",
        'RESOURCE_VIEW_SKILL_RELATIONSHIP': "View Skill Relationship",
        'RESOURCE_VIEW_JOB_ASSIGNMENTS': "View Job Assignments",
        'RESOURCE_BUILD_SCHEDULE': "Build Schedule",
        'RESOURCE_DELETE_EVENT': "Delete Event",
        'RESOURCE_UPDATE_AVAILABILITY': "Update Availability",
        'RESOURCE_UPDATE_WORK_ADDRESS': "Update Work Address",
        'RESOURCE_UPDATE_LOCATION': "Update Location",
        'RESOURCE_VIEW_VOLUNTEER': "View Volunteer",
        'RESOURCE_ADD_EVENT': "Add Event",
        'RESOURCE_UPDATE_SKILL': "Update Skill",
        'RESOURCE_VIEW_JOBS': "View Jobs",
        'RESOURCE_VIEW_RESOURCES': "View Resources",
        'RESOURCE_UPDATE_RELATIONSHIP': "Update Relationship",
        'RESOURCE_VIEW_EVENT': "View Event",
        'RESOURCE_VIEW_LOCATION': "View Location",
        'RESOURCE_VIEW_VOLUNTEER_SKILL': "View Volunteer Skill",
        'RESOURCE_VIEW_EVENT_PREFERENCE': "View Event Preference",
        'RESOURCE_ADD_SKILL': "Add Skill",
        'RESOURCE_UPDATE_SECURITY_GROUP_PRIVILEGE': "Update Security Group Privilege",
        'RESOURCE_UPDATE_SKILL_RELATIONSHIP': "Update Skill Relationship",
        'RESOURCE_VIEW_PRIVILEGES': "View Privileges",
        'RESOURCE_VIEW_RELATIONSHIP': "View Relationship",
        'RESOURCE_HOME': "Home",
        'RESOURCE_ADD_AVAILABILITY': "Add Availability",
        'RESOURCE_UPDATE_SCHEDULE': "Update Schedule",
        'RESOURCE_VALIDATE_RELATIONSHIP': "Validate Relationship",
        'RESOURCE_VIEW_SKILL': "View Skill",
        'RESOURCE_UPDATE_HOUSEHOLD': "Update Household",
        'RESOURCE_UPDATE_VOLUNTEER_SKILL': "Update Volunteer Skill",
        'RESOURCE_VIEW_SECURITY_GROUPS': "View Security Groups",
        'RESOURCE_PASSWORD_RESET': "Password Reset",
        'RESOURCE_ADD_JOB': "Add Job",
        'RESOURCE_DELETE_VOLUNTEER': "Delete Volunteer",
        'RESOURCE_VIEW_RELATIONSHIPS': "View Relationships",
        'RESOURCE_VIEW_HELP': "View Help",
        'RESOURCE_UPDATE_JOB': "Update Job",
        'RESOURCE_VIEW_JOB_ASSIGNMRNTS': "View Job Assignments",
        'RESOURCE_ADD_JOB_ASSIGNMRNTS': "Add Job Assignments",
        'RESOURCE_UPDATE_JOB_ASSIGNMRNTS': "Update Job Assignments",
        'RESOURCE_DELETE_JOB_ASSIGNMRNTS':"Delete Job Assignments",
        'RESOURCE_DELETE_CONFIGURABLE_PROPERTY': "Delete Configurable Property",
        'RESOURCE_UPDATE_EVENT': "Update Event",
        'RESOURCE_ADD_SKILL_RELATIONSHIP': "Add Skill Relationship",
        'RESOURCE_DELETE_LOCATION': "Delete Location",
        'RESOURCE_DELETE_RESOURCE': "Delete Resource",
        'RESOURCE_VIEW_REPORTS': "View Reports",
        'RESOURCE_DELETE_JOB': "Delete Job",
        'RESOURCE_VIEW_SCHEDULE': "View Schedule",
        'RESOURCE_ADD_LOCATION': "Add Location",
        'RESOURCE_UPDATE_CONFIGURABLE_PROPERTY': "Update Configurable Property"
        'RESOURCE_SKILL_RELATIONSHIP_UPDATE': "Update Skill Relationship",
        'RESOURCE_ADD_LOGIN': "Add Login",
        'RESOURCE_ADD_SECURITY_GROUP_PRIVILEGE': "Add Security Group Privilege",
        'RESOURCE_VIEW_JOB':"View Job",
        'RESOURCE_ADD_HOUSEHOLD': "Add Household",
        'RESOURCE_UTILITIES': "Utilities",
        'RESOURCE_DELETE_VOLUNTEER_SKILL': "Delete Volunteer Skill",
        'RESOURCE_ADD_REPORT': "Add Report",
        'RESOURCE_ADD_VOLUNTEER': "Add Volunteer",
        'RESOURCE_NOT_AUTHORIZED': "Not Authorized",
        'RESOURCE_VIEW_SECURITY_GROUP_PRIVILEGE': "View Security Group Privilege",
        'RESOURCE_VIEW_RESOURCE': "View Resource",
        'RESOURCE_VIEW_SKILLS': "View Skills",
        'RESOURCE_UPDATE_RESOURCE': "Update Resource",
        'RESOURCE_VIEW_SCHEDULES': "View Schedules",
        'RESOURCE_ADD_RELATIONSHIP': "Add Relationship",
        'RESOURCE_DELETE_SKILL_RELATIONSHIP': "Delete Skill Relationship",
        'RESOURCE_UPDATE_PRIVILEGE': "Update Privilege", 
        'RESOURCE_UPDATE_LOGIN': "Update Login",
        'RESOURCE_UPDATE_EVENT_PREFERENCE': "Update Event Preference",
        'RESOURCE_UPDATE_SECURITY_GROUP': "Update Security Group",
        'RESOURCE_VIEW_CONFIGURABLE_PROPERTIES': "View Configurable Properties",
        'RESOURCE_DELETE_HOUSEHOLD': "Delete Household",
        'RESOURCE_ADD_RESOURCE': "Add Resource",
        'RESOURCE_DELETE_AVAILABILITY': "Delete Availability",
        'RESOURCE_VIEW_HOUSEHOLDS': "View Households",
        'RESOURCE_ADD_PRIVILEGE': "Add Privilege",
        'RESOURCE_ADD_CONFIGURABLE_PROPERTY': "Add Configurable Property",
        'RESOURCE_VIEW_AVAILABILITY': "View Availability"
    }
    
    def __init__(self):
        pass
    
    def authorize(self, action):
        result: False
        login: self.sessionData.getCurrentLogin()
        if login:
            self.sessionData
            result = SecurityUtils.isAuthorized(login, action)
        return result
