from django.urls import include, path
from django.views.generic import TemplateView
#from debug_toolbar.toolbar import debug_toolbar_urls
from . import views

app_name = "vs"
urlpatterns = [
    path("", views.initial, name="initial"),
    path("dash", views.dashboard_view, name="dashboard"),
    path("vs/addOrganization", views.AddOrganizationView.as_view(), name="addOrganization"),
    path("vs/addLocation", views.AddLocationView.as_view(), name="addLocation"),
    path("vs/addSkill", views.AddSkillView.as_view(), name="addSkill"),
    path("vs/assignments", views.DummyView.as_view(), name="assignments"),
    path("vs/events", views.DummyView.as_view(), name="events"),
    path("vs/forgotPassword", views.DummyView.as_view(), name="forgotPassword"),
    path("vs/help", views.HelpView.as_view(), name="help"),
    path("vs/home/", views.Home.as_view(), name="home"),
    path("vs/households", views.HouseholdsView.as_view(), name="households"),
    path("vs/householdDetails", views.DummyView.as_view(), name="householdDetailss"),
    path("vs/login/", views.LoginView.as_view(), name="tryLogin"),
    path("vs/loginHtml/", TemplateView.as_view(template_name='vs/login.html'), name='loginHtml'),
    path("vs/logout/", views.logout, name="tryLogout"),
    path("vs/locationEdit", views.LocationEditView.as_view(), name="locationEdit"),
    path("vs/locations", views.LocationsView.as_view(), name="locations"),
    path("vs/locationUpdate", views.LocationUpdateView.as_view(), name="locationUpdate"),
    path("vs/organizationEdit", views.OrganizationEditView.as_view(), name="OrganizationEdit"),
    path("vs/organizationSelect", views.OrganizationSelectView.as_view(), name="organizationSelect"),
    path("vs/organizationSelected", views.OrganizationSelectedView.as_view(), name="organizationSelect"),
    path("vs/organizations", views.OrganizationsView.as_view(), name="organizations"),
    path("vs/organizationUpdate", views.OrganizationUpdateView.as_view(), name="organizationUpdate"),
    path("vs/passwordChange", views.DummyView.as_view(), name="passwordChange"),
    path("vs/projects", views.DummyView.as_view(), name="projects"),
    path("vs/resources", views.ResourcesView.as_view(), name="resources"),
    path("vs/reports", views.DummyView.as_view(), name="reports"),
    path("vs/schedules", views.DummyView.as_view(), name="schedules"),
    path("vs/skillEdit", views.SkillEditView.as_view(), name="skillEdit"),
    path("vs/skills", views.SkillsView.as_view(), name="skills"),
    path("vs/skillUpdate", views.SkillUpdateView.as_view(), name="skillUpdate"),
    path("vs/utilities", views.DummyView.as_view(), name="utilities"),
    path("vs/volunteerHome", views.DummyView.as_view(), name="volunteerHome"),
    path("vs/volunteerAvailability", views.DummyView.as_view(), name="volunteerAvailability"),
    path("vs/volunteerEventPreferences", views.DummyView.as_view(), name="volunteerEventPreferences"),
    path("vs/volunteerJobAssignments", views.DummyView.as_view(), name="volunteerJobAssignments"),
    path("vs/volunteerRelationships", views.DummyView.as_view(), name="volunteerRelationships"),
    path("vs/volunteers", views.VolunteersView.as_view(), name="volunteers"),
] #+ debug_toolbar_urls()