# Generated by Django 6.0.7 on 2026-10-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dborganization',
            name='organizationName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
